version: '3.3'

services:
  web:
    build: .
    container_name: es-doc-web
    restart: unless-stopped
    volumes:
      # Монтирование для разработки (раскомментируйте при наличии репы с ассетами(es-doc-assets) в директории с приложением или рядом с ним)
      # - ../es-doc-assets:/app/content
      - ./static:/app/static
      - ./templates:/app/templates
      - temp_data:/app/temp
    environment:
      - ES_DOC_ASSETS_PATH=/app/content
      - ES_DOC_CACHE_PATH=/app/temp
      - ES_DOC_SITE_URL=https://es-doc.sovue.org
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: es-doc-nginx
    ports:
      - "8005:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  temp_data:
  
