/* Run against a local ES Doc server. Set NODE_PATH to bundled Node packages. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {chromium} = require('playwright');
const target = process.env.CHARACTERS_TEST_URL || 'http://127.0.0.1:8013/tools/characters';
(async () => {
    const browser = await chromium.launch({headless:true});
    const page = await browser.newPage({viewport:{width:1440,height:1100}});
    const errors = []; page.on('pageerror',error => errors.push(error.message));
    try {
        await page.goto(target); await page.locator('#characters-app').waitFor({state:'visible'});
        const code = () => page.locator('#character-code').inputValue();
        assert.equal(await page.locator('.page-title').textContent(),'Создатель простых персонажей');
        assert.equal(await page.locator('#character-name-mode,#character-all-settings,#character-value-who_size').count(),0);
        await page.locator('#character-name').fill(''); assert.match(await code(),/Character\(\s*None/);
        assert(await page.locator('#character-namebox').isHidden());
        await page.locator('#character-name').fill('player_name');
        await page.locator('#character-dynamic').check(); assert.match(await code(),/dynamic=True/);
        assert(await page.locator('#character-dynamic-warning').isVisible());
        const name = await page.locator('#character-preview-who').textContent();
        await page.waitForTimeout(200); assert.notEqual(await page.locator('#character-preview-who').textContent(),name);
        await page.locator('#character-color-who_color').fill('#123456');
        await page.locator('#character-value-what_underline').selectOption('True');
        await page.locator('#character-value-what_strikethrough').selectOption('True');
        assert.equal(await page.locator('#character-preview-what').evaluate(el => el.style.textDecoration),'underline line-through');
        await page.locator('#character-kind').selectOption('un'); assert.match(await code(),/kind=un/);
        assert.match(await code(),/who_color="#123456"/);
        await page.locator('#character-kind').selectOption('custom');
        await page.locator('#character-custom-kind').fill('my_character');
        assert.match(await code(),/kind=my_character/); assert.match(await code(),/who_color="#123456"/);
        await page.locator('#character-value-what_suffix').fill('!'); assert.match(await code(),/what_suffix="!"/);
        await page.locator('#character-value-who_font').fill('fonts/custom.ttf');
        assert.match(await code(),/who_font="fonts\/custom.ttf"/);
        assert.match(await page.locator('#character-help-who_font').textContent(),/невозможно предсмотреть/);
        await page.locator('#character-variable').fill('bad name'); assert(await page.locator('#character-copy').isDisabled());
        await page.locator('#character-fix-error').click(); assert.equal(await page.evaluate(() => document.activeElement.id),'character-variable');
        await page.locator('#character-variable').fill('e');
        const saved = await code(); await page.locator('#character-reset').click(); await page.locator('#character-undo').click(); assert.equal(await code(),saved);
        await page.reload(); await page.locator('#characters-app').waitFor({state:'visible'}); assert.equal(await code(),saved);
        const draft = await page.evaluate(() => localStorage.getItem('es-doc-character-draft-v1'));
        await page.locator('#character-reset').click();
        await page.locator('#character-project-file').setInputFiles({name:'character.json',mimeType:'application/json',buffer:Buffer.from(draft)});
        await page.waitForFunction(() => document.querySelector('#character-code').value.includes('kind=my_character'));
        assert.equal(await code(),saved);
        await page.emulateMedia({reducedMotion:'reduce'}); await page.locator('#character-name').fill('player_name_reduced');
        const reduced = await page.locator('#character-preview-who').textContent(); await page.waitForTimeout(200); assert.equal(await page.locator('#character-preview-who').textContent(),reduced);
        await page.locator('#character-dynamic').uncheck();
        const background = await page.locator('#character-dialogue-window').evaluate(el => getComputedStyle(el).backgroundImage);
        assert.match(background,/dialogue_box\/day\/dialogue_box.png/);
        const artwork = await page.request.get(new URL('/resource/raw/images/gui/dialogue_box/day/dialogue_box.png',target).href); assert.equal(artwork.status(),200);
        await page.locator('#character-kind').selectOption('');
        await page.locator('#character-name').fill('Семён');
        await page.locator('#character-value-who_color').fill('');
        await page.locator('#character-value-what_underline').selectOption(''); await page.locator('#character-value-what_strikethrough').selectOption('');
        const geometry = await page.locator('#character-dialogue-window').evaluate(el => {
            const box = el.getBoundingClientRect(), who = document.querySelector('#character-preview-who').getBoundingClientRect(), what = document.querySelector('#character-preview-what').getBoundingClientRect();
            return {ratio:box.width/box.height,whoX:(who.left-box.left)/box.width,whoY:(who.top-box.top)/box.height,whatY:(what.top-box.top)/box.height};
        });
        assert(Math.abs(geometry.ratio - 1572/151) < .02,'Original dialogue artwork must keep its aspect ratio');
        assert(Math.abs(geometry.whoX - 20/1572) < .002,'Name keeps the original left inset');
        assert(Math.abs(geometry.whoY - 15/151) < .01,'Name keeps the original vertical inset');
        assert(Math.abs(geometry.whatY - 48/151) < .01,'Dialogue starts below the original name tab');
        await page.locator('#character-preview-heading').scrollIntoViewIfNeeded();
        await page.screenshot({path:'temp/characters-desktop.png'});
        await page.setViewportSize({width:390,height:844});
        await page.locator('#character-preview-heading').scrollIntoViewIfNeeded();
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
        await page.screenshot({path:'temp/characters-mobile.png'});
        await page.locator('#character-zoom').click();
        assert.equal(await page.locator('#character-zoom').getAttribute('aria-pressed'),'true');
        const zoom = await page.locator('#character-stage').evaluate(el => {const box=el.getBoundingClientRect(); return {width:box.width,ratio:box.width/box.height};});
        assert(zoom.width >= 960); assert(Math.abs(zoom.ratio-1572/151) < .02);
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),'Zoom scroll stays inside the preview');
        await page.locator('#character-name').fill('Имя'.repeat(100)); await page.locator('#character-sample').fill('Длинная реплика '.repeat(100));
        const longRatio = await page.locator('#character-stage').evaluate(el => el.clientWidth/el.clientHeight);
        assert(Math.abs(longRatio - 1572/151) < .1,'Long text must not stretch the artwork');
        await page.locator('#character-zoom').click();

        await page.locator('.page-back').click(); await page.waitForURL('**/tools'); await page.goBack(); await page.locator('#characters-app').waitFor({state:'visible'});
        assert.deepEqual(errors,[]); console.log('Character browser checks passed (desktop/mobile, dynamic/reduced motion, inheritance, export, draft and undo).');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
