/* Run against a local ES Doc server. Set NODE_PATH to the bundled Node packages. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {chromium} = require('playwright');
const target = process.env.CHARACTERS_TEST_URL || 'http://127.0.0.1:8013/tools/characters';

(async () => {
    const browser = await chromium.launch({headless:true});
    const page = await browser.newPage({viewport:{width:1440,height:1100},colorScheme:'light'});
    const errors = [], writes = [];
    page.on('pageerror',error => errors.push(error.message));
    page.on('request',request => { if (request.method() !== 'GET') writes.push(request.url()); });
    try {
        await page.goto(target); await page.locator('#characters-app').waitFor({state:'visible'});
        const code = () => page.locator('#character-code').inputValue();
        assert.equal(await code(), 'define e = Character("Семён")');
        assert(await page.locator('#character-value-who_color').isVisible(),'Common appearance controls are immediately available');
        assert(await page.locator('#character-name-mode').isHidden(),'Name semantics are disclosed on request');
        assert(await page.locator('#character-mode-who_color').isHidden(),'Python mode does not compete with basic color input');
        assert.equal(await page.locator('#character-zoom').getAttribute('aria-pressed'),'true');
        await page.locator('#character-color-who_color').fill('#123456');
        assert.match(await code(), /who_color="#123456"/);
        await page.locator('#character-value-who_color').fill('');
        assert.equal(await code(), 'define e = Character("Семён")','Clearing a basic field restores inheritance');
        await page.locator('#character-value-who_color').fill('#abc8');
        assert.match(await code(), /who_color="#abc8"/);
        assert.equal(await page.locator('#character-preview-who').evaluate(el => el.style.color), 'rgba(170, 187, 204, 0.533)');
        await page.locator('#character-what-fields').locator('..').locator('summary').first().click();
        await page.locator('#character-value-what_bold').selectOption('False');
        assert.match(await code(), /what_bold=False/);
        await page.locator('#character-identity-options > summary').click();
        await page.locator('#character-name-mode').selectOption('none');
        assert(await page.locator('#character-namebox').isHidden());
        assert.match(await code(), /Character\(\n    None,/);
        await page.locator('#character-name-mode').selectOption('text');
        await page.locator('#character-name').fill('Имя "с кавычками"');
        assert.match(await code(), /\\"с кавычками\\"/);
        await page.locator('#character-variable').fill('bad name');
        assert(await page.locator('#character-copy').isDisabled());
        assert.equal(await page.locator('#character-variable').getAttribute('aria-invalid'),'true');
        await page.locator('#character-fix-error').click();
        assert.equal(await page.evaluate(() => document.activeElement.id),'character-variable');
        await page.locator('#character-variable').fill('e');
        await page.locator('#character-value-who_size').fill('42');
        const saved = await code();
        await page.locator('#character-reset').click();
        assert.equal(await code(), 'define e = Character("Семён")');
        await page.locator('#character-undo').click();
        assert.equal(await code(),saved);
        await page.locator('#character-all-settings > summary').click();
        await page.locator('#character-property-search').fill('скорость');
        assert((await page.locator('#character-property option').allTextContents()).some(text => text.includes('what_slow_cps')));
        await page.locator('#character-property-search').fill('who_color');
        await page.locator('#character-switch-scope').click();
        assert.equal(await page.locator('#character-property-scope').inputValue(),'who');
        assert.equal(await page.locator('#character-property').inputValue(),'who_color');
        await page.locator('#character-property-scope').selectOption('what');
        await page.locator('#character-property-search').fill('outlines');
        await page.locator('#character-add-property').click();
        await page.locator('#character-remove-what_outlines').click();
        assert.equal(await page.locator('#character-value-what_outlines').count(),0,'An empty added field can be removed');
        await page.locator('#character-add-property').click();
        await page.locator('#character-value-what_outlines').fill('[(2, "#000", 0, 1)]');
        assert.match(await code(), /what_outlines=\[\(2, "#000", 0, 1\)\]/);
        assert(await page.locator('#character-preview-what').evaluate(el => Boolean(el.style.textShadow)));
        await page.locator('#character-value-what_outlines').fill('[(2, "#000", 0, 1)');
        assert(await page.locator('#character-copy').isDisabled());
        await page.locator('#character-value-what_outlines').fill('[(2, "#000", 0, 1)]');
        await page.locator('.character-custom-disclosure > summary').click();
        await page.locator('#character-custom-key').fill('show_myflag');
        await page.locator('#character-add-custom').click();
        await page.locator('#character-value-show_myflag').fill('True');
        assert.match(await code(), /show_myflag=True/);
        assert(await page.locator('#character-preview-limitations').isVisible());
        await page.locator('#character-property-search').fill('padding');
        await page.locator('#character-property-scope').selectOption('window');
        await page.locator('#character-property').selectOption('window_padding');
        await page.locator('#character-add-property').click();
        await page.locator('#character-value-window_padding').fill('(20, 60)');
        const padding = await page.locator('#character-dialogue-window').evaluate(el => ({x:parseFloat(getComputedStyle(el).paddingLeft),y:parseFloat(getComputedStyle(el).paddingTop)}));
        assert(Math.abs(padding.y / padding.x - 3) < .01,'RenPy two-tuple padding is horizontal then vertical');
        await page.locator('#character-value-window_padding').fill('(10, 20, 30, 40)');
        const edges = await page.locator('#character-dialogue-window').evaluate(el => ['paddingLeft','paddingTop','paddingRight','paddingBottom'].map(key => parseFloat(getComputedStyle(el)[key])));
        assert(edges.every((v,i) => Math.abs(v / edges[0] - (i+1)) < .01),'RenPy four-tuple order is left/top/right/bottom');
        await page.locator('#character-sample').fill('{b}Жирно{/b} {color=#f00}Красно{/color}');
        await page.locator('#character-replay').click();
        assert.equal(await page.locator('#character-preview-what span').count(),2,'Replay preserves inline formatting while revealing text');
        await page.locator('#character-stage').click();
        await page.locator('#character-sample').fill('Я говорю так!');
        const data = await page.evaluate(() => localStorage.getItem('es-doc-character-draft-v1'));
        const file = {name:'e.character.json',mimeType:'application/json',buffer:Buffer.from(data)};
        await page.locator('#character-reset').click();
        await page.locator('#character-project-file').setInputFiles(file);
        await page.waitForFunction(() => document.querySelector('#character-code').value.includes('show_myflag=True'));
        await page.reload();
        await page.locator('#characters-app').waitFor({state:'visible'});
        assert.match(await code(), /show_myflag=True/);
        const download = page.waitForEvent('download');
        await page.locator('#character-download').click();
        const artifact = await download; assert.equal(artifact.suggestedFilename(),'e.rpy');
        assert.match(fs.readFileSync(await artifact.path(),'utf8'),/show_myflag=True/);
        await page.locator('#character-copy').click();
        await page.waitForFunction(() => /скопировано|выделен/.test(document.querySelector('#character-status').textContent));
        assert.match(await page.locator('#character-status').textContent(), /скопировано|выделен/);
        await page.locator('.character-preview-options').first().locator('summary').click();
        await page.locator('#character-font-who').setInputFiles('static/fonts/inter-variable-cyrillic.woff2');
        await page.waitForFunction(() => document.querySelector('#character-preview-who').style.fontFamily.includes('character-preview-who'));
        await page.locator('#character-clear-fonts').click();
        assert.equal(await page.locator('#character-preview-who').evaluate(el => el.style.fontFamily),'');
        await page.locator('#character-background-file').setInputFiles('static/img/favicon.webp');
        await page.waitForFunction(() => document.querySelector('#character-stage').style.backgroundImage.includes('blob:'));
        await page.locator('#character-clear-background').click();
        assert.equal(await page.locator('#character-stage').evaluate(el => el.style.backgroundImage),'');
        await page.locator('#character-identity-options > summary').click();
        await page.locator('#character-name-mode').selectOption('expression');
        await page.locator('#character-name').fill('get_name');
        await page.locator('#character-preview-name').fill('Алиса');
        assert.equal(await page.locator('#character-preview-who').textContent(),'Алиса');
        await page.locator('#character-name-mode').selectOption('text');
        await page.locator('a.page-back').click();
        await page.waitForURL('**/tools');
        assert.equal(await page.evaluate(() => window.__esdocCharactersCleanup),null);
        await page.locator('a[href="/tools/characters"]').click();
        await page.locator('#characters-app').waitFor({state:'visible'});
        assert.match(await code(), /show_myflag=True/);
        await page.locator('#character-reset').click();
        await page.locator('.character-field').filter({has:page.locator('#character-value-who_color')}).locator('.character-field-options > summary').click();
        await page.locator('#character-enabled-who_color').check();
        assert.match(await code(), /who_color=""/,'Explicit empty strings remain representable');
        await page.locator('#character-remove-who_color').click();
        assert.equal(await code(),'define e = Character("Семён")');
        await page.evaluate(() => document.querySelectorAll('#characters-app details').forEach(el => el.open = false));
        fs.mkdirSync('.impeccable/review',{recursive:true});
        for (const [name,width,theme] of [['characters-desktop',1440,'light'],['characters-desktop-dark',1440,'dark'],['characters-medium',1280,'light'],['characters-mobile',390,'light'],['characters-mobile-dark',390,'dark']]) {
            // Isolate theme/viewport capture from the integration page and its scroll state.
            const capture = await browser.newPage({viewport:{width,height:width > 720 ? 1100 : 844},colorScheme:theme});
            await capture.emulateMedia({reducedMotion:'reduce'});
            await capture.goto(target);
            await capture.locator('#characters-app').waitFor({state:'visible'});
            await capture.evaluate(() => document.fonts.ready);
            assert(await capture.evaluate(() => document.documentElement.scrollWidth <= innerWidth),name + ' overflow');
            assert(await capture.locator('#character-preview-what').evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 16),name + ' readable initial preview');
            await capture.screenshot({path:'.impeccable/review/' + name + '.png',fullPage:true});
            if (width > 720) await capture.screenshot({path:'.impeccable/review/' + name + '-preview.png',clip:await capture.locator('#character-stage').boundingBox()});
            else await capture.locator('#character-stage').screenshot({path:'.impeccable/review/' + name + '-preview.png'});
            await capture.close();
            console.log('Captured ' + name);
        }
        await page.setViewportSize({width:390,height:844});
        await page.locator('#character-value-who_size').fill('36');
        await page.locator('[data-character-jump="code"]').click();
        assert.equal(await page.evaluate(() => document.activeElement.id),'character-code-heading');
        assert(await page.locator('[data-character-jump="settings"]').isVisible());
        await page.locator('[data-character-jump="settings"]').click();
        assert.equal(await page.evaluate(() => document.activeElement.id),'character-value-who_size','Return navigation restores the last edited field');
        await page.locator('[data-character-jump="code"]').click();
        await page.keyboard.press('Control+z');
        assert.equal(await code(),'define e = Character("Семён")','Undo shortcut works outside text editors');
        assert.deepEqual(errors,[]); assert.deepEqual(writes,[]);
        console.log('Character workbench integration passed.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
