import assert from 'node:assert/strict';
import { test } from 'node:test';
import fs from 'node:fs';
import vm from 'node:vm';

const context = vm.createContext({});
vm.runInContext(fs.readFileSync(new URL('../static/js/tools-core.js', import.meta.url), 'utf8'), context);
const core = context.ESDocTools;

test('PYC is accepted and unsupported versions have specific advice', () => {
    assert.equal(core.accepts('module.PYC', 'combined'), true)
    assert.equal(core.accepts('module.pyc', 'unrpyc'), true)
    assert.equal(core.accepts('module.pyc', 'unrpa'), false)
    const error = core.explainError('module.pyc: PYC: байткод Python 3.9 не поддерживается. Доступны версии до Python 3.8.')
    assert.equal(error.path, 'module.pyc')
    assert.match(error.title, /Версия Python не поддерживается/)
    assert.match(error.explanation, /оригинал/)
    assert.equal(error.tryHarder, false)
})

test('PYC source-preservation warning identifies the original input', () => {
    const warning = core.explainWarning('pkg/module.pyc: Исходный файл pkg/module.py уже есть в архиве, сохранён без замены.')
    assert.equal(warning.path, 'pkg/module.pyc')
    assert.equal(warning.title, 'Сохранён готовый исходник')
    assert.match(warning.explanation, /\.py/)
})

test('errors preserve technical details but explain invalid input without claiming obfuscation', () => {
    const technical = 'Traceback (most recent call last):\n  /tools/engine.py\nunrpyc.BadRpycException: Invalid RPYC';
    const error = core.explainError(technical, 'bad.rpyc');
    assert.equal(error.path, 'bad.rpyc');
    assert.match(error.title, /формат сценария/);
    assert.match(error.explanation, /файл из папки игры/);
    assert.equal(error.tryHarder, false);
    assert.equal(error.technical, technical);
    const unknown = core.explainError('<script>unknown failure</script>');
    assert.match(unknown.title, /Не удалось обработать/);
    assert.equal(unknown.technical, '<script>unknown failure</script>');
});

test('only changed script structure offers advanced recovery; memory and network have separate advice', () => {
    assert.equal(core.explainError('Unable to find the right slot to load from the rpyc file. The file header structure has been changed.').tryHarder, true);
    assert.match(core.explainError('MemoryError: Out of memory').explanation, /меньше файлов/);
    assert.match(core.explainError('TypeError: Failed to fetch dynamically imported module').explanation, /соединение/);
    const archive = core.explainError('game/data.rpa: UnknownArchiveError: unsupported header');
    assert.equal(archive.path, 'game/data.rpa');
    assert.match(archive.title, /формат архива/);
});

test('filter extensions by tool, including uppercase and modules', () => {
    assert.equal(core.accepts('game/SCRIPT.RPYC', 'unrpyc'), true);
    assert.equal(core.accepts('game/file.rpymc', 'combined'), true);
    assert.equal(core.accepts('game/data.rpa', 'combined'), true);
    assert.equal(core.accepts('game/data.rpa', 'unrpyc'), false);
    assert.equal(core.accepts('game/a.png', 'combined'), false);
});
test('reject unsafe paths before passing files to worker', () => {
    for (const path of ['../file', '/absolute', 'C:\\file', 'a/../../b', 'a\0b']) {
        assert.throws(() => core.safePath(path));
    }
    assert.equal(core.safePath('game/сцены/script.rpyc'), 'game/сцены/script.rpyc');
});

test('read every batch of a dropped folder and preserve nested paths', async () => {
    const file = name => ({ isFile: true, name, file: done => done({ name, size: 1 }) });
    const folder = (name, batches) => ({ isDirectory: true, name, createReader: () => ({
        readEntries: done => done(batches.shift() || []),
    }) });
    const entry = folder('game', [[file('a.rpyc')], [folder('scenario', [[file('b.rpyc')], []])], []]);
    const paths = [];
    await core.walkEntry(entry, '', item => paths.push(item.path));
    assert.deepEqual(paths, ['game/a.rpyc', 'game/scenario/b.rpyc']);
});

test('permission errors from folder enumeration propagate', async () => {
    const entry = { name: 'blocked', isDirectory: true, createReader: () => ({
        readEntries: (done, error) => error(new Error('permission denied')),
    }) };
    await assert.rejects(core.walkEntry(entry, '', () => {}), /permission denied/);
});

test('legacy RenPy warnings explain successful decompilation and possible inaccuracies', () => {
    for (const version of [6, 7]) {
        const message = `game/сцены/script.rpyc: Warning: analysis found signs that this .rpyc file was generated by ren'py \n    version ${version} or below, while this unrpyc version targets ren'py \n    version 8. Decompilation will still be attempted, but errors or incorrect \n    decompilation might occur. `;
        const warning = core.explainWarning(message);
        assert.equal(warning.path, 'game/сцены/script.rpyc');
        assert.match(warning.explanation, /Файл декомпилирован\./);
        assert.match(warning.explanation, new RegExp(`Ren'Py ${version} или более ранней`));
        assert.match(warning.explanation, /вероятно/);
        assert.match(warning.explanation, /возможны ошибки и неточности/);
        assert.equal(warning.technical, message);
    }
});

test('structural and custom-displayable warnings give distinct explanations', () => {
    const structure = core.explainWarning('Warning: Encountered an unexpected slot structure. It is possible the \n    file header structure has been changed.');
    assert.equal(structure.title, 'Изменённая структура файла');
    const displayable = core.explainWarning('Warning: Encountered a user-defined displayable of type "Custom".\n For now the style name "custom_style" will be substituted.');
    assert.match(displayable.explanation, /«custom_style»/);
    assert.match(displayable.explanation, /renpy.register_sl_displayable/);
});

test('existing source is not described as decompiled, and recovery attempts are explained', () => {
    const source = core.explainWarning('script.rpymc: Исходный файл script.rpym уже есть в архиве, сохранён без замены.');
    assert.equal(source.path, 'script.rpymc');
    assert.match(source.explanation, /повторная декомпиляция этого файла не выполнялась/);
    const recovery = core.explainWarning('Attempting to deobfuscate file:\n strategy first failed\n strategy second success');
    assert.match(recovery.explanation, /Неудачные промежуточные попытки/);
    assert.match(recovery.explanation, /Файл восстановлен/);
});

test('unknown messages retain original details and do not invent a specific cause', () => {
    const message = '<script>unknown diagnostic</script>\n more details';
    const warning = core.explainWarning(message);
    assert.equal(warning.title, 'Результат требует проверки');
    assert.equal(warning.technical, message);
    assert.match(warning.explanation, /Файл получен/);
    assert.equal(warning.path, '');
});

test('container warnings distinguish extracted blocks and missing Python source', () => {
    const partial = core.explainWarning('script.rpyc: Контейнер: Python-блок содержит только байткод. Исходник не восстановлен, в .rpy оставлены комментарий и pass.')
    assert.equal(partial.title, 'Python-блок восстановлен частично');
    assert.match(partial.explanation, /pass/);
    assert.match(partial.explanation, /не восстановлен/);
    const extracted = core.explainWarning('Контейнер: восстановлено блоков: 18. Они добавлены ниже основного скрипта для чтения и адаптации.')
    assert.equal(extracted.title, 'Извлечены блоки сценария')
    assert.match(extracted.explanation, /загрузчик/i);
    const failed = core.explainWarning('Контейнер: блок 0 не восстановлен (ValueError). Исходный контейнер оставлен в .rpy.')
    assert.equal(failed.title, 'Не удалось раскрыть контейнер')
    assert.match(failed.explanation, /сохранён/);
});

