import assert from 'node:assert/strict';
import { test } from 'node:test';
import fs from 'node:fs';
import vm from 'node:vm';

const context = vm.createContext({});
vm.runInContext(fs.readFileSync(new URL('../static/js/tools-core.js', import.meta.url), 'utf8'), context);
const core = context.ESDocTools;

test('filter extensions by tool, including uppercase and modules', () => {
    assert.equal(core.accepts('game/SCRIPT.RPYC', 'unrpyc'), true);
    assert.equal(core.accepts('game/file.rpymc', 'combined'), true);
    assert.equal(core.accepts('game/data.rpa', 'combined'), true);
    assert.equal(core.accepts('game/data.rpa', 'unrpyc'), false);
    assert.equal(core.accepts('game/a.png', 'combined'), false);
});
test('reject unsafe paths before passing files to worker', () => {
    for (const path of ['../file', '/absolute', 'C:\\file', 'a/../../b', 'a\0b']) {
        assert.throws(() => core.safePath(path));
    }
    assert.equal(core.safePath('game/сцены/script.rpyc'), 'game/сцены/script.rpyc');
});

test('read every batch of a dropped folder and preserve nested paths', async () => {
    const file = name => ({ isFile: true, name, file: done => done({ name, size: 1 }) });
    const folder = (name, batches) => ({ isDirectory: true, name, createReader: () => ({
        readEntries: done => done(batches.shift() || []),
    }) });
    const entry = folder('game', [[file('a.rpyc')], [folder('scenario', [[file('b.rpyc')], []])], []]);
    const paths = [];
    await core.walkEntry(entry, '', item => paths.push(item.path));
    assert.deepEqual(paths, ['game/a.rpyc', 'game/scenario/b.rpyc']);
});

test('permission errors from folder enumeration propagate', async () => {
    const entry = { name: 'blocked', isDirectory: true, createReader: () => ({
        readEntries: (done, error) => error(new Error('permission denied')),
    }) };
    await assert.rejects(core.walkEntry(entry, '', () => {}), /permission denied/);
});

test('legacy RenPy warnings explain successful decompilation and possible inaccuracies', () => {
    for (const version of [6, 7]) {
        const message = `game/сцены/script.rpyc: Warning: analysis found signs that this .rpyc file was generated by ren'py \n    version ${version} or below, while this unrpyc version targets ren'py \n    version 8. Decompilation will still be attempted, but errors or incorrect \n    decompilation might occur. `;
        const warning = core.explainWarning(message);
        assert.equal(warning.path, 'game/сцены/script.rpyc');
        assert.match(warning.explanation, /Файл декомпилирован\./);
        assert.match(warning.explanation, new RegExp(`Ren’Py ${version} или более ранней`));
        assert.match(warning.explanation, /вероятно/);
        assert.match(warning.explanation, /возможны ошибки и неточности/);
        assert.equal(warning.technical, message);
    }
});

test('structural and custom-displayable warnings give distinct explanations', () => {
    const structure = core.explainWarning('Warning: Encountered an unexpected slot structure. It is possible the \n    file header structure has been changed.');
    assert.equal(structure.title, 'Изменённая структура файла');
    const displayable = core.explainWarning('Warning: Encountered a user-defined displayable of type "Custom".\n For now the style name "custom_style" will be substituted.');
    assert.match(displayable.explanation, /«custom_style»/);
    assert.match(displayable.explanation, /renpy.register_sl_displayable/);
});

test('existing source is not described as decompiled, and recovery attempts are explained', () => {
    const source = core.explainWarning('script.rpymc: Исходный файл script.rpym уже есть в архиве, сохранён без замены.');
    assert.equal(source.path, 'script.rpymc');
    assert.match(source.explanation, /повторная декомпиляция этого файла не выполнялась/);
    const recovery = core.explainWarning('Attempting to deobfuscate file:\n strategy first failed\n strategy second success');
    assert.match(recovery.explanation, /Неудачные промежуточные попытки/);
    assert.match(recovery.explanation, /Файл восстановлен/);
});

test('unknown messages retain original details and do not invent a specific cause', () => {
    const message = '<script>unknown diagnostic</script>\n more details';
    const warning = core.explainWarning(message);
    assert.equal(warning.title, 'Результат требует проверки');
    assert.equal(warning.technical, message);
    assert.match(warning.explanation, /Файл получен/);
    assert.equal(warning.path, '');
});

