"""Refresh the property names/types from the official Ren'Py style reference.

Run with the site's Python: scripts/prepare_character_catalog.py [saved-style.html].
The generated catalog is committed; visitors never fetch external documentation.
"""
import html
import json
import re
import sys
from pathlib import Path
from urllib.request import urlopen

SOURCE = 'https://www.renpy.org/doc/html/style_properties.html'
ROOT = Path(__file__).resolve().parents[1]


def generate(source):
    group = ''
    result = []
    tokens = re.finditer(r'<section id="([^"]+)">|<dt[^>]*id="style-property-([^"]+)"[^>]*>(.*?)</dt>', source, re.DOTALL)
    for match in tokens:
        if match[1]:
            if match[1].endswith('-style-properties'):
                group = match[1].removesuffix('-style-properties')
            continue
        signature = html.unescape(re.sub('<[^>]+>', '', match[3])).replace('\uf0c1', '').strip()
        datatype = signature.split(' -', 1)[-1].strip()
        mode = 'expression'
        if datatype == 'boolean':
            mode = 'boolean'
        elif datatype in ('int', 'float'):
            mode = 'number'
        elif datatype in ('string', 'color'):
            mode = 'text'
        result.append({'name': match[2], 'type': datatype, 'mode': mode, 'group': group})
    if len(result) < 120:
        raise ValueError('Incomplete style reference')
    catalog = {'source': SOURCE, 'version': '8.5.4', 'styles': result}
    output = '// Generated by scripts/prepare_character_catalog.py from the official Ren\'Py reference.\n'
    output += 'window.ESDocCharacterCatalog = ' + json.dumps(catalog, ensure_ascii=False, indent=2) + ';\n'
    (ROOT / 'static/js/characters-catalog.js').write_text(output, 'utf-8')
    print(f'{len(result)} style properties written')


if __name__ == '__main__':
    source = Path(sys.argv[1]).read_text('utf-8') if len(sys.argv) > 1 else urlopen(SOURCE).read().decode('utf-8')
    generate(source)
