"""Rebuild browser icons from the checked-in canonical Lucide SVGs (no network)."""
import json
import re
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICON_DIR = ROOT / 'static' / 'icons'


def browser_source():
    manifest = json.loads((ICON_DIR / 'manifest.json').read_text('utf-8'))
    bodies = {
        name: (ICON_DIR / f'{name}.svg').read_text('utf-8').split('>', 1)[1].rsplit('</svg>', 1)[0].strip()
        for name in manifest['icons']
    }
    return '''/* Generated by scripts/sync_lucide_icons.py from the vendored Lucide SVGs.
   License and pinned upstream revision: static/icons/. */
(function () {
    'use strict';
    const bodies = ''' + json.dumps(bodies, ensure_ascii=False, indent=4) + ''';
    const escape = value => String(value).replace(/[&<>"']/g, c => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    })[c]);
    window.ESDocIcons = Object.freeze({
        svg(name, size = 18, className = '') {
            if (!Object.hasOwn(bodies, name)) throw new Error('Unknown Lucide icon: ' + name);
            if (!Number.isInteger(size) || size < 1 || size > 128) throw new Error('Invalid icon size');
            const classes = 'lucide lucide-' + name + (className ? ' ' + className : '');
            return '<svg xmlns="http://www.w3.org/2000/svg" class="' + escape(classes) +
                '" width="' + size + '" height="' + size +
                '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"' +
                ' stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">' +
                bodies[name] + '</svg>';
        },
    });
})();
'''


if __name__ == '__main__':
    (ROOT / 'static' / 'js' / 'icons.js').write_text(browser_source(), encoding='utf-8')
    def mask_url(match):
        name = match[1]
        source = (ICON_DIR / f'{name}.svg').read_text('utf-8')
        digest = hashlib.sha1(source.encode('utf-8')).hexdigest()[:12]
        return f'/static/icons/{name}.svg?v={digest}'
    for filename in ('tools.css', 'resources.css', 'doc.css', 'warpers.css'):
        path = ROOT / 'static' / 'css' / filename
        source = path.read_text('utf-8')
        source = re.sub(
            r'/static/icons/([a-z0-9-]+)\.svg(?:\?v=[a-f0-9]+)?',
            mask_url, source,
        )
        path.write_text(source, encoding='utf-8')
